### ISSUE TITLE
Please provide more info for MCU in RV1106

### ISSUE THREAD

**Issue by luyi1888** [LuckfoxTECH/luckfox-pico#10]
Hi
I figure out how to run the bare-metal app on RISC-V MCU in RV1106. I'm using LuckFox Pico Pro board.
But it seens like the performance is odd slow.
Does rockchip provide some document for this MCU? If yes, can you upload it?

Also, how to connect the JTAG for MCU?
According to the datasheet, they use 2-wire JTAG interface for Cortex-A/HPMCU/LPMCU. Is it cJTAG?
I can confirm the Cortex-A is SWD. I already use CMSIS-DAP connected it.

```
Dhrystone Benchmark, Version C, Version 2.2
Program compiled with 'register' attribute
Using rdcycle(), HZ=1000000

Trying 500 runs through Dhrystone:
Final values of the variables used in the benchmark:

Int_Glob:            5
        should be:   5
Bool_Glob:           1
        should be:   1
Ch_1_Glob:           A
        should be:   A
Ch_2_Glob:           B
        should be:   B
Arr_1_Glob[8]:       7
        should be:   7
Arr_2_Glob[8][7]:    510
        should be:   Number_Of_Runs + 10
Ptr_Glob->
  Ptr_Comp:          125991984
        should be:   (implementation-dependent)
  Discr:             0
        should be:   0
  Enum_Comp:         2
        should be:   2
  Int_Comp:          17
        should be:   17
  Str_Comp:          DHRYSTONE PROGRAM, SOME STRING
        should be:   DHRYSTONE PROGRAM, SOME STRING
Next_Ptr_Glob->
  Ptr_Comp:          125991984
        should be:   (implementation-dependent), same as above
  Discr:             0
        should be:   0
  Enum_Comp:         1
        should be:   1
  Int_Comp:          18
        should be:   18
  Str_Comp:          DHRYSTONE PROGRAM, SOME STRING
        should be:   DHRYSTONE PROGRAM, SOME STRING
Int_1_Loc:           5
        should be:   5
Int_2_Loc:           13
        should be:   13
Int_3_Loc:           7
        should be:   7
Enum_Loc:            1
        should be:   1
Str_1_Loc:           DHRYSTONE PROGRAM, 1'ST STRING
        should be:   DHRYSTONE PROGRAM, 1'ST STRING
Str_2_Loc:           DHRYSTONE PROGRAM, 2'ND STRING
        should be:   DHRYSTONE PROGRAM, 2'ND STRING

Microseconds for one run through Dhrystone: 2891
Dhrystones per Second:                      34
mcycle = 14332013
minstret = 212532

```

**Comment by luckfox-eng33** [comment]
rockchip not provide some document for this MCU
connect the JTAG for MCU，Please refer to the [RV1106 Datasheet](https://files.luckfox.com/wiki/Luckfox-Pico/PDF/Rockchip%20RV1106%20%20V1.3-20230522.pdf)
![image](https://github.com/LuckfoxTECH/luckfox-pico/assets/144299491/ef6c7f43-c74a-4b0c-9f71-78a95f34562e)

**Comment by andrethomas** [comment]
@luckfox-eng33 I wonder if the LPMCU implementation is not similar to what is seen on the SG2002 used by milk-v https://github.com/milkv-duo/duo-buildroot-sdk/tree/develop/freertos/cvitek insofar that its built into the buildroot image and not directly programmable externally?

**Comment by luyi1888** [comment]
@andrethomas There is LPMCU_BOOT_ADDR register in PMU_SGRF. I think it should have the same boot sequences as HPMCU. But all rockchip provided MCU firmware binary are loaded to HPMCU. So it is not easy to figure out how to use LPMCU. Maybe LPMCU is the same as HPMCU just running at lower frequency or completely different.

**Comment by andrethomas** [comment]
@luyi1888 yeah thanks, I understand it will likely remain a mystery for a long time if not forever :)

**Comment by andrethomas** [comment]
For reference, there is new information at issue https://github.com/LuckfoxTECH/luckfox-pico/issues/99
