### ISSUE TITLE
What is the buildroot username and password?

### ISSUE THREAD

**Issue by nopnop2002** [LuckfoxTECH/luckfox-pico#106]
I downloaded Luckfox_pico_mini_a_image from drive.google.com.

I wrote the firmware to the SD card and turned on the MINI board.

What is the buildroot username and password?

![Luckfox-mini-buildroot-11](https://github.com/LuckfoxTECH/luckfox-pico/assets/6020549/94a4e2cc-6440-4f1d-8bd7-2348698aaee5)

**Comment by luckfox-eng33** [comment]
https://wiki.luckfox.com/Luckfox-Pico/SSH-Telnet-Login/
```
Login: root
Password: luckfox
Static IP: 172.32.0.93
```

**Comment by nopnop2002** [comment]
thank you.
I was able to log in.
![Luckfox-mini-buildroot-12](https://github.com/LuckfoxTECH/luckfox-pico/assets/6020549/babd3dd3-1c1c-47b4-ad65-949f43014f70)
