### ISSUE TITLE
About custom buildroot

### ISSUE THREAD

**Issue by nopnop2002** [LuckfoxTECH/luckfox-pico#109]
I created a custom buildroot according to Wiki.
Everything went well.
Your documentation is excellent.

I have 4 questions.

(Q1)
According to Wiki, the steps are as follows.

```
cd <SDK directory>/tools/linux/toolchain/arm-rockchip830-linux-uclibcgnueabihf/
source env_install_toolchain.sh
cd <SDK directory>
# When compiling Ubuntu, be sure to use sudo to avoid file system errors.
sudo ./build.sh lunch
sudo ./build.sh
cd sysdrv/source/buildroot/buildroot-2023.02.6/
```

"buildroot-2023.02.6" directory is not present immediately after downloading the SDK. It is necessary to compile the SDK once before this directory becomes available.
For files included in buildroot-2023.02.6, the file owner and group are inappropriate, so we need to change the owner and group of all files.

```
sudo chown -R my_user:my_group /home/nop/luckfox-pico/sysdrv/source/buildroot/buildroot-2023.02.6
```

(Q2)
According to Wiki, the steps are as follows.

```
cd <SDK directory>/sysdrv/source/buildroot/buildroot-2023.02.6/
make luckfox_pico_defconfig
make menuconfig
make savedefconfig 
make

cd <SDK directory>
# When compiling Ubuntu, be sure to use sudo to avoid file system errors.
sudo ./build.sh lunch
sudo ./build.sh
```

Is savedefconfig necessary?

(Q3)
Static IP address of the USB virtual dongle is 172.32.0.93.
With a custom buildroot, can we change this?

![Luckfox-mini-buildroot-12](https://github.com/LuckfoxTECH/luckfox-pico/assets/6020549/441f1043-19b5-4b4f-a7b4-302e6acf36c7)

(Q4)

After running build.sh, build.sh changes the owner of some files.
make causes the following error:
We have to manually delete the directory.
```
cd <SDK directory>/sysdrv/source/buildroot/buildroot-2023.02.6/
make luckfox_pico_defconfig
make menuconfig
make savedefconfig 
make

cd <SDK directory>
# When compiling Ubuntu, be sure to use sudo to avoid file system errors.
sudo ./build.sh lunch
sudo ./build.sh
# build.sh changes the owner of some files.

cd <SDK directory>/sysdrv/source/buildroot/buildroot-2023.02.6/
make menuconfig
make

>>>   Generating root filesystems common tables
rm -rf /home/nop/luckfox-pico/sysdrv/source/buildroot/buildroot-2023.02.6/output/build/buildroot-fs
rm: cannot remove '/home/nop/luckfox-pico/sysdrv/source/buildroot/buildroot-2023.02.6/output/build/buildroot-fs/full_users_table.txt': Permission denied
rm: cannot remove '/home/nop/luckfox-pico/sysdrv/source/buildroot/buildroot-2023.02.6/output/build/buildroot-fs/full_devices_table.txt': Permission denied
rm: cannot remove '/home/nop/luckfox-pico/sysdrv/source/buildroot/buildroot-2023.02.6/output/build/buildroot-fs/tar/fakeroot': Permission denied
make[1]: *** [fs/common.mk:77: rootfs-common] Error 1
make: *** [Makefile:82: _all] Error 2


sudo rm -r output/build/buildroot-fs/
make

```

**Comment by luckfox-eng33** [comment]
1. If you use buildroot, we recommend using `./build.sh` instead of `sudo ./build.sh`
2. If you do not use automatic compilation scripts later, it is not necessary, but it is necessary if you need automatic compilation scripts `build.sh`.
3. You can check `sysdrv/tools/board/android-tools/S90usb0config` by yourself
4. Same as question 1, `sudo` is only required when building ubuntu, which involves permission issues.

**Comment by nopnop2002** [comment]
@luckfox-eng33 

Thank you for answering.
