### ISSUE TITLE
How to create single image for flashing sd card direclty without SocToolkit?

### ISSUE THREAD

**Issue by chaguidiao** [LuckfoxTECH/luckfox-pico#12]
Say, doing this with dd command.  I presume this requires the need to know the partition starting address for each *.img but don't know how to do it exactly.  For luckfox-pico (without the plus).

**Comment by luckfox-eng33** [comment]
It depends on your partition. The partition is determined by RK_PARTITION_CMD_IN_ENV in the corresponding MK file.
The MK file is stored under {SDK_PATH}/project/cfg/BoardConfig_IPC/
Take BoardConfig-SPI_NAND-NONE-RV1106_Luckfox_Pico_Pro_Max-IPC.mk as an example

```
export RK_PARTITION_CMD_IN_ENV="256K(env),256K@256K(idblock),512K(uboot),4M(boot),30M(oem),10M(userdata),210M(rootfs)"
```
The starting position of the first partition(env) is 0x00000000 and the size is 256K
The starting position of the second partition(idblock) is 0x00040000 (256K) and the size is 256K
and so on


* There is also a simple method. Use SOC TOOLKIT to open the corresponding image file and you can see the corresponding starting position.
![image](https://github.com/LuckfoxTECH/luckfox-pico/assets/144299491/25579470-6fb7-42dc-9f3d-aa1ef26f18b8)
