### ISSUE TITLE
Pico_Ultra_W cannot use Alpine,refund

### ISSUE THREAD

**Issue by peterwillcn** [LuckfoxTECH/luckfox-pico#134]
Ok, the Pico_Ultra_W cannot use Alpine, and I have given up. I am returning and requesting a refund for the RV1106_Luckfox_Pico_Ultra_W.

**Comment by luckfox-eng33** [comment]
如果你需要退货，你可以联系你的经销商，并不需要在此处声明

**Comment by luckfox-eng33** [comment]
If you need to return a product, you can contact your dealer and do not need to declare it here
