### ISSUE TITLE
Introduce My Ubuntu fork for pico max

### ISSUE THREAD

**Issue by CmST0us** [LuckfoxTECH/luckfox-pico#15]
I have adapot ubuntu 22.04 for pico max, sd card boot image.
If you interesting to this, pls review this repo.

`https://github.com/CmST0us/luckfox-pico`

**Comment by CmST0us** [comment]
login password and username is both `pico`

**Comment by luckfox-eng33** [comment]
Nice. Thank you for your contribution.
We are very interested and will communicate with you after testing.
