### ISSUE TITLE
OTA images cannot be built

### ISSUE THREAD

**Issue by sh1970** [LuckfoxTECH/luckfox-pico#153]
I want to output OTA image but it fails, how to fix this, thanks.
Seems to be missing script RK_OTA_update.sh
Here's the build log:

guest@notebook-12:/my_work/IOT/luckfox-pico-iot$ ./build.sh ota
**************************************
Check [OK]: dtc --version
**************************************
Check [OK]: makeinfo --version
**************************************
Check [OK]: gperf --version
**************************************
Check [OK]: dpkg --list |grep g++-.*-multilib
**************************************
Check [OK]: dpkg --list |grep gcc-.*-multilib
**************************************
Check [OK]: make -v
GLOBAL_PARTITIONS: 0x40000@0x0(env),0x40000@0x40000(idblock),0x80000@0x80000(uboot),0x400000@0x100000(boot),0xA00000@0x500000(oem),0xA00000@0xF00000(userdata),0xE600000@0x1900000(rootfs)
[build.sh:info] Partition Filesystem Type Configure: rootfs@IGNORE@ubifs,oem@/oem@ubifs,userdata@/userdata@ubifs
uboot.img
boot.img
tar: system.img: Cannot stat: No such file or directory
tar: RK_OTA_update.sh: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
[build.sh:error] Running build_ota failed!
[build.sh:error] exit code 2 from line 759:
[build.sh:info]     tar -cvhf /my_work/IOT/luckfox-pico-iot/output/image/update_ota.tar -C /my_work/IOT/luckfox-pico-iot/output/image uboot.img boot.img system.img -C /my_work/IOT/luckfox-pico-iot/output/out/ramdisk RK_OTA_update.sh

**Comment by luckfox-eng33** [comment]
We have not tested OTA, and the RK_OTA_update.sh file does not exist in the original SDK provided by RK.
