### ISSUE TITLE
Luckfox Pico Mini A - Run yolov8

### ISSUE THREAD

**Issue by ret7020** [LuckfoxTECH/luckfox-pico#157]
Hello! I can run Yolov5 on Luckfox Pico Mini A and it works, But when I try to run yolov8 demo from rknn_model_zoo repo it crashes:

```bash
[root@luckfox rknn_yolov8_demo]# ./rknn_yolov8_demo model/yolov8.rknn model/bus.
jpg 
load lable ./model/coco_80_labels_list.txt
E RKNN: failed to decode config data!
Segmentation fault (core dumped)
```

**Comment by luckfox-eng33** [comment]
I think you can ask in [rknn](https://github.com/airockchip/rknn-toolkit2)
