### ISSUE TITLE
Configure GPIO in Uboot

### ISSUE THREAD

**Issue by bousong** [LuckfoxTECH/luckfox-pico#163]
Can we configure gpio pins in, for example, the board_init() function, in Uboot instead of kernel device tree? I've looked through the path "project/sysdrv/source/uboot/u-boot/board/rockchip" and cannot be able to find board.c

**Comment by luckfox-eng33** [comment]
`sysdrv/source/uboot/u-boot/board/rockchip/evb_rv1106`
You can refer to this evb_rv1106, but we have not tested it
We don't usually modify uboot directly
