### ISSUE TITLE
luckfox-config I can only export PWM7_M1 and PWM3_M1, all others says that GPIOX and PWM cannnot be enabled at the same time

### ISSUE THREAD

**Issue by vjoco** [LuckfoxTECH/luckfox-pico#187]
I'm trying to use PWM in luckfox ultra w

 except PWM7_M1 and  PWM3_M1, I cannot enable PWM, luckfox-config says that the corresponding GPIO and PWM cannot be used at the same time. 

 Beside, PWM3_M1 does not output PWM. 
 Only PWM7_M1  works.
 
 I need two channels.. 

 what can I do.

 any idea?

**Comment by vjoco** [comment]
I found it by myself basically.... 
If you disable RGB in luckfox-config, that will release all LCD pins... which are everywhere.. Am I right, RGB is in fact LCD interface?
 Now PWM is working

**Comment by luckfox-eng33** [comment]
Yes, RGB is the LCD interface, and it will take up a lot of GPIOs.
