### ISSUE TITLE
project/cfg/BoardConfig_IPC/BoardConfig-SD_CARD-Buildroot-RV1103_Luckfox_Pico_Mini_B-IPC.mk 出现问题，无法编译

### ISSUE THREAD

**Issue by hzr12** [LuckfoxTECH/luckfox-pico#188]

**Comment by hzr12** [comment]
BoardConfig-SD_CARD-Buildroot-RV1103_Luckfox_Pico_Mini_B-IPC.mk 中的 export RK_KERNEL_DTS=rv1103g-luckfox-pico-mini-b.dts 修改为export RK_KERNEL_DTS=rv1103g-luckfox-pico-mini.dts 就能编译

**Comment by hzr12** [comment]
log:
[log.txt](https://github.com/user-attachments/files/17586329/log.txt)

**Comment by luckfox-eng33** [comment]
收到反馈，后续会统一使用rv1103g-luckfox-pico-mini.dts
