### ISSUE TITLE
关于快速启动

### ISSUE THREAD

**Issue by steven-spec** [LuckfoxTECH/luckfox-pico#198]
我看官方介绍 1.4 提供rv1106使用spi_nand和emmc快速启动的支持，我烧录了1.4的镜像，但是启动时间还是要几秒和之前版本的效果差不多。请问是需要在编译选项里面选择什么项，还是要做其他什么配置呢？
我的设备是：Luckfox Pico Ultra

**Comment by luckfox-eng29** [comment]
您好 ，由于RV1106的快速启动跳过了uboot在kernel实现硬件的初始化会导致很多功能无法使用，目前我们的快速启动配置仅能构建只读系统，所以快速启动的配置是单独分出来的，使用./build.sh lunch后选择[8]，其中两个带FASTBOOT后缀的即为快速启动的配置项，后续我们会根据社区反馈决定是否进一步开发。

**Comment by steven-spec** [comment]
> 您好 ，由于RV1106的快速启动跳过了uboot在kernel实现硬件的初始化会导致很多功能无法使用，目前我们的快速启动配置仅能构建只读系统，所以快速启动的配置是单独分出来的，使用./build.sh lunch后选择[8]，其中两个带FASTBOOT后缀的即为快速启动的配置项，后续我们会根据社区反馈决定是否进一步开发。

明白了，谢谢！
