### ISSUE TITLE
使用build.sh 之后 ，所有make menuconfig 的修改都回重置了

### ISSUE THREAD

**Issue by epenli** [LuckfoxTECH/luckfox-pico#30]
当我在 luckfox-pico/sysdrv/source/buildroot/buildroot-2023.02.6 中 使用 make menuconfig 修改了任何东西 ，
只要在项目目录下 ./build.sh 修改过的任何配置 都被还原了 ， 请问要如何修改

**Comment by luckfox-eng33** [comment]
build.sh指定了对应的配置文件，并且你没有保存到默认配置，请参考[Buildroot](https://wiki.luckfox.com/zh/Luckfox-Pico/Luckfox-Buildroot)

**Comment by andrethomas** [comment]
This is OK for adding support, but if you remove something, e.g. Samba, it does not remove it from the rootfs... need some other method to force a complete rebuild of the rootfs?
