### ISSUE TITLE
RV1106 Complete User Manual data sheet

### ISSUE THREAD

**Issue by Francky400** [LuckfoxTECH/luckfox-pico#36]
HI,

Please, where i can download the full complete Rockchip RV1106 Datasheet (user reference manual, registers description, .....)

Thanks in advance

HANSEN Franck

**Comment by luckfox-eng33** [comment]
Hello
Due to problems with ROCKCHIP, we cannot provide the corresponding files directly. You can check doc(https://files.luckfox.com/wiki/Luckfox-Pico/PDF/doc.7z） first

**Comment by EricH45** [comment]
Hello,
The link to the docs is not usable. Does it changed ?
Regards,
Eric H

**Comment by luckfox-eng33** [comment]
> Hello, The link to the docs is not usable. Does it changed ? Regards, Eric H

It may be a problem with github. You can download it from our wiki.
https://wiki.luckfox.com/Luckfox-Pico/Datasheets
![image](https://github.com/LuckfoxTECH/luckfox-pico/assets/144299491/28245c45-27fc-4e83-9fd5-aecfa31671d0)
