### ISSUE TITLE
Configuration Interface for Luckfox Pico Mini A

### ISSUE THREAD

**Issue by versamodule** [LuckfoxTECH/luckfox-pico#43]
I have the Pico Mini A, and I would like to add Ethernet to it. 
I have bought the same RJ45 ethernet connector that is used on the LuckFox Pico Plus. 
From what I gather it need to re-compile the kernel to add Ethernet. I was reading here: 
https://wiki.luckfox.com/Luckfox-Pico/Luckfox-Pico-Menuconfig/

that is says:

> Execute the following command to open the configuration interface:
> 
> cd <SDK directory>/sysdrv/source/kernel
> cp ./arch/arm/configs/luckfox_rv1106_linux_defconfig .config
> make ARCH=arm menuconfig
> 

But this is not for my pico Mini A, so what would I do here ?

**Comment by luckfox-eng33** [comment]
Refer to the mk file, it seems you have found the solution.

**Comment by platima** [comment]
Hey @versamodule 

@luckfox-eng33 is trying to "teach a man to fish" :P

Not wrong though, this has the exact instruction: https://wiki.luckfox.com/Luckfox-Pico/Luckfox-Pico-SDK#4-modifying-device-tree

I have also just built a Luckfox Pico Mini (B) Ubuntu image with gmac enabled. Works on Mini A too: https://github.com/platima/sbc-images/tree/main/Luckfox/Pico

Enjoy!
