### ISSUE TITLE
Luckfox Pico Mini B, build fails

### ISSUE THREAD

**Issue by seulater** [LuckfoxTECH/luckfox-pico#47]
Using ./build.sh lunch and selecting option #6  BoardConfig_IPC/BoardConfig-SPI_NAND-Buildroot-RV1103_Luckfox_Pico_Mini_B-IPC.mk
The build fails with the following. 

> [mkfs_ubi.sh:info] Start build ubi images...
> /usr/bin/fakeroot
> [mkfs_ubi.sh:info] ubifs_lebsize=0x20000
> [mkfs_ubi.sh:info] ubifs_miniosize=2048
> [mkfs_ubi.sh:info] ubifs_maxlebcnt=247
> [mkfs_ubi.sh:info] ubifs compression support: lzo|zlib !!!
> [mkfs_ubi.sh:warn]  is not support, default use lzo !!!
> 
> [mkfs_ubi.sh:info] ubifs_lebsize=0x40000
> [mkfs_ubi.sh:info] ubifs_miniosize=2048
> [mkfs_ubi.sh:info] ubifs_maxlebcnt=121
> [mkfs_ubi.sh:info] ubifs compression support: lzo|zlib !!!
> [mkfs_ubi.sh:warn]  is not support, default use lzo !!!
> 
> [mkfs_ubi.sh:info] ubifs_lebsize=0x40000
> [mkfs_ubi.sh:info] ubifs_miniosize=4096
> [mkfs_ubi.sh:info] ubifs_maxlebcnt=123
> [mkfs_ubi.sh:info] ubifs compression support: lzo|zlib !!!
> [mkfs_ubi.sh:warn]  is not support, default use lzo !!!
> 
> start build fakeroot image
> fakeroot, while creating message channels: Function not implemented
> This may be due to a lack of SYSV IPC support.
> fakeroot: error while starting the `faked' daemon.
> /usr/bin/fakeroot: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
> kill -l [exitstatus]
> [mkfs_ubi.sh:error] Running main failed!
> [mkfs_ubi.sh:error] exit code 1 from line 341:
> [mkfs_ubi.sh:info]     $FAKEROOT_TOOL -- $ROOTFS_IMAGE_FAKEROOT_UBI
> [build.sh:error] Running build_mkimg failed!
> [build.sh:error] exit code 1 from line 1742:
> [build.sh:info]     $RK_PROJECT_TOOLS_MKFS_UBIFS $src $(dirname $dst) $part_size $part_name $fs_type $RK_UBIFS_COMP

Yet, if I select option 0, 1 or 2 (thats what else I have tried) it compiles with no errors. 
Any ideas why it failing for the Mini-B which is what I have.

**Comment by luckfox-eng33** [comment]
Have you modified the mk file? Your ubi file image seems to be abnormally large.
When I compile the thing, the message I get is
```
[mkfs_ubi.sh:info] Start build ubi images...
/usr/bin/fakeroot
[mkfs_ubi.sh:info] ubifs_lebsize=0x20000
[mkfs_ubi.sh:info] ubifs_miniosize=2048
[mkfs_ubi.sh:info] ubifs_maxlebcnt=82
[mkfs_ubi.sh:info] ubifs compression support: lzo|zlib !!!
[mkfs_ubi.sh:warn]  is not support, default use lzo !!!

[mkfs_ubi.sh:info] ubifs_lebsize=0x40000
[mkfs_ubi.sh:info] ubifs_miniosize=2048
[mkfs_ubi.sh:info] ubifs_maxlebcnt=40
[mkfs_ubi.sh:info] ubifs compression support: lzo|zlib !!!
[mkfs_ubi.sh:warn]  is not support, default use lzo !!!

[mkfs_ubi.sh:info] ubifs_lebsize=0x40000
[mkfs_ubi.sh:info] ubifs_miniosize=4096
[mkfs_ubi.sh:info] ubifs_maxlebcnt=41
[mkfs_ubi.sh:info] ubifs compression support: lzo|zlib !!!
[mkfs_ubi.sh:warn]  is not support, default use lzo !!!

```

**Comment by luckfox-eng33** [comment]
Please make sure you use wsl as wsl2
* How to confirm which wsl version you are using
    `wsl -l -v`
* Set WSL version to 2
    `wsl --set-version <distribution name> <versionNumber>`
* Perhaps you can use Microsoft's documentation as a reference
    https://learn.microsoft.com/en-us/windows/wsl/basic-commands
