### ISSUE TITLE
Will there be tutorials for LVGL in the future?

### ISSUE THREAD

**Issue by dazzy2003** [LuckfoxTECH/luckfox-pico#5]

**Comment by luckfox-eng33** [comment]
Maybe, but lvgl already has a very complete official tutorial

**Comment by dazzy2003** [comment]
> Maybe, but lvgl already has a very complete official tutorial

In fact, I would like to know how to port LVGL onto this board?

**Comment by bonuschild** [comment]
> Maybe, but lvgl already has a very complete official tutorial

Yeah but if luckfox could provide a real tutorial would be much more better :)

Hope this will come as soon as possible!

**Comment by luckfox-eng33** [comment]
A simple LVGL example
https://wiki.luckfox.com/Luckfox-Pico/Luckfox-Pico-LVGL

**Comment by andrethomas** [comment]
Great work @luckfox-eng33, closing this one for now thanks
