### ISSUE TITLE
How to disable RNDIS and connect usb ethernet dongle?

### ISSUE THREAD

**Issue by hrshovon** [LuckfoxTECH/luckfox-pico#50]
hello,
I have a luckfox pico mini B. I am trying to enable usb host and connect an usb ethernet dongle. I managed to do that. But I am not getting any ip address via dhcp. I see a lot of messages like udhcpc is broadcasting discover. May be some startup script is preventing dhcp. Please help

**Comment by luckfox-eng33** [comment]
1. You need to open the kernel line and identify the corresponding device
2. You need to check if there is a corresponding eth interface through `ifconfig -a` ![image](https://github.com/LuckfoxTECH/luckfox-pico/assets/144299491/422f6028-7a9a-4b7f-9b72-f4d287e26c74)
3. Then use `udhcpc -i eth*` to obtain the corresponding IP，like`udhcpc -i eth1` ![image](https://github.com/LuckfoxTECH/luckfox-pico/assets/144299491/b36c8b08-068b-433d-b073-e6e1981d87da)
