### ISSUE TITLE
Can "./build.sh" be compiled using multithreading? Similar to "make -j 12"

### ISSUE THREAD

**Issue by xxfg1** [LuckfoxTECH/luckfox-pico#54]

**Comment by luckfox-eng33** [comment]
build.sh will perform multithread compilation
but in many cases it can only perform single-core compilation due to dependency issues.

**Comment by jeason1997** [comment]
build.sh 
line: 36-40
`if [ `getconf _NPROCESSORS_ONLN` -eq 1 ]; then
	export RK_JOBS=1
else
	export RK_JOBS=$((`getconf _NPROCESSORS_ONLN` - 1 ))
fi`
It will automatically use multithreading
