### ISSUE TITLE
Changing rtsp configuration

### ISSUE THREAD

**Issue by csvke** [LuckfoxTECH/luckfox-pico#55]
I cannot find documentation anywhere else but it seems configuration of the rtsp streams can be changed in
`/oem/user/share/rkipc-300w.ini`
As I have a Luckfox Pico Max 256M connected to the SC3336 Cam that is 300W

And after making changes, reboot is needed.

Are there documentation as to provide more details?

**Comment by luckfox-eng33** [comment]
hi
RKIPC has provided the source code. 
Please check the source code yourself. 
Rockchip does not provide more documentation.

**Comment by csvke** [comment]
> hi RKIPC has provided the source code. Please check the source code yourself. Rockchip does not provide more documentation.

Where is the source code?

**Comment by luckfox-eng33** [comment]
[project/app/rkipc/rkipc](https://github.com/LuckfoxTECH/luckfox-pico/tree/main/project/app/rkipc/rkipc)
and
[project/app/rkipc/rkipc/docs/Rockchip_Developer_Guide_Linux_RKIPC_CN.md](https://github.com/LuckfoxTECH/luckfox-pico/blob/main/project/app/rkipc/rkipc/docs/Rockchip_Developer_Guide_Linux_RKIPC_CN.md)
