### ISSUE TITLE
PPP add support for Pico Pro/Max

### ISSUE THREAD

**Issue by meox** [LuckfoxTECH/luckfox-pico#56]
Can you add support for PPP module in the SD-Card image of Ubuntu?
I need it to run openvpn and openforti.

**Comment by luckfox-eng33** [comment]
hi
You can enable the corresponding module in your own kernel, which may be more flexible for you.

**Comment by meox** [comment]
yes I did it but only works if the module is compiled "static"

**Comment by luckfox-eng33** [comment]
So it works fine, right?

**Comment by meox** [comment]
Yes!

Il sab 6 gen 2024, 08:01 luckfox-eng33 ***@***.***> ha
scritto:

**Comment by luckfox-eng33** [comment]
Okay, then I'll feel at ease
