### ISSUE TITLE
Is there a image for Alpine Linux available?

### ISSUE THREAD

**Issue by DerPicknicker** [LuckfoxTECH/luckfox-pico#59]
Hey, 

just a small question I want to use the Pico Max but for me it's not clear where I can find the compatible Linux versions for this small machine. Or let's say it in different words: Which Linux distribution are compatible?

In addition to the question above I want to know if I can connect a usb c hub to the USB port to use an external soundcard or WiFi dongle. 

Best regards

**Comment by EngineerWill** [comment]
It is compatible with busybox by default, but we also ported Ubuntu. 
Other Linux distributions need to be ported by themselves. 
Fortunately, a user contributed a post on how to port Alpine Linux, which we also reproduced in the wiki.[Luckfox-Pico-Alpine-Linux-2](https://wiki.luckfox.com/Luckfox-Pico/Luckfox-Pico-Alpine-Linux-2)

**Comment by EngineerWill** [comment]
hey，
It is compatible with busybox by default, but we also ported Ubuntu. 
Other Linux distributions need to be ported by themselves. 
Fortunately, a user contributed a post on how to port Alpine Linux, which we also reproduced in the wiki.[Luckfox-Pico-Alpine-Linux-2](https://wiki.luckfox.com/Luckfox-Pico/Luckfox-Pico-Alpine-Linux-2)

**Comment by DerPicknicker** [comment]
Hey @EngineerWill , 

thank you for the fast response could you link the Ubuntu image? Or do I have to compile it on my own? A already built image would be great and makes it easier to use for simple projects

**Comment by EngineerWill** [comment]
luckfox provide [image](https://drive.google.com/drive/folders/1sFUWjYpDDisf92q9EwP1Ia7lHgp9PaFS)

**Comment by DerPicknicker** [comment]
Thank you for the link. And then just follow the steps on the wiki I guess. This seems like a great small project for me.

**Comment by andrethomas** [comment]
I just followed the wiki and built an alpinelinux image as the one provided is missing a few things like the ntp setup which makes it difficult to use apk via ssl. I like the small footprint as a well featured distro that can run from spi-nand... I think I may build a sd card image also since apk is working well already.
