### ISSUE TITLE
Supported image sensors

### ISSUE THREAD

**Issue by pragulka** [LuckfoxTECH/luckfox-pico#62]
Hello,

What image sensors does LuckFox RV1103/6 support?

**Comment by pragulka** [comment]
And is there USB UVC support?

**Comment by luckfox-eng33** [comment]
https://wiki.luckfox.com/Core3566/Core3566-pinout/7.%20USB%20Camera/#7-1-%E6%B5%8B%E8%AF%95usb-%E6%91%84%E5%83%8F%E5%A4%B4

**Comment by andrethomas** [comment]
Is there a pinout available for the camera connector/port ?
