### ISSUE TITLE
CV/ML libs integration

### ISSUE THREAD

**Issue by tair-rhyme** [LuckfoxTECH/luckfox-pico#63]
Hello.
I'm planning to use Luckfox Pico Max to computer vision project.
Are you planning to integrate such libraries or make instructions to make it happen: [tflite](https://www.tensorflow.org/lite), [sod](https://sod.pixlab.io/index.html)?

**Comment by luckfox-eng33** [comment]
There may be no plans for the short term
However, we encourage users to port and share relevant experiences, and we issue rewards based on their contributions to the community.

Welcome to [Luckfox forum](https://forums.luckfox.com) for discussion
