### ISSUE TITLE
how to use npu

### ISSUE THREAD

**Issue by xinshuwei** [LuckfoxTECH/luckfox-pico#7]
Can you tell me，how to use npu？ I will use luckfox setup deep learning machine

**Comment by luckfox-eng33** [comment]
The corresponding tutorial will be released in the future.
Now temporarily can refer to[rknn-toolkit2](https:github.com/rockchip-linux/rknn-toolkit2)

**Comment by andrethomas** [comment]
Do you have an updated link? The one you provided above is not working
