### ISSUE TITLE
rootfs_uclibc_rv1106.tar missing

### ISSUE THREAD

**Issue by uraich** [LuckfoxTECH/luckfox-pico#71]
When trying to build the firmware I get 
[build.sh:error] Not found rootfs tarball: /opt/ucc/micros/luckfox/luckfox-pico/output/out/sysdrv_out/rootfs_uclibc_rv1106.tar

**Comment by andrethomas** [comment]
Can you list your build steps?

**Comment by uraich** [comment]
git clone https://github.com/LuckfoxTECH/luckfox-pico.git
cd luckfox-pico
./build.sh lunch      selected option 5
./build.sh firmware
![Screenshot from 2024-02-20 14-24-28](https://github.com/LuckfoxTECH/luckfox-pico/assets/1673533/e7478c22-9f42-4b04-9595-829ff932c7a9)

**Comment by uraich** [comment]
Found the problem! I was missing the 
build.sh 
step before build.sh firmware
