### ISSUE TITLE
High loadavg

### ISSUE THREAD

**Issue by andrethomas** [LuckfoxTECH/luckfox-pico#72]
Hi,

Any ideas what causes the skewed or high load avg when booting from nand?

```
# uptime
 23:54:57 up 3 min,  load average: 5.96, 2.81, 1.09
#
```

It keeps fluctuating around 5.50 to 8.50 but I can't find any obvious source of the "load"

![image](https://github.com/LuckfoxTECH/luckfox-pico/assets/470015/50fc8ac8-2cd4-4c41-b5c2-cb3802ec90e1)

**Comment by luckfox-eng33** [comment]
You can get references from the forums
https://forums.luckfox.com/viewtopic.php?t=90

**Comment by andrethomas** [comment]
It must be something to do with the factory image, maybe 1103 vs 1106 I'm not sure - works fine if you self compile an image to run from spi-nand so closing this one.

**Comment by andrethomas** [comment]
Turns out it was one or more of the oem kernel modules, probably camera related as I do not have a camera  to connect to this board.
