### ISSUE TITLE
Ramdon MAC address

### ISSUE THREAD

**Issue by andrethomas** [LuckfoxTECH/luckfox-pico#73]
Hi,

I note that for each reboot a new random MAC address is "generated?" which is problematic with DHCP reservations and although I understand its benefits from a privacy perspective it would be nice to know where to change this to be static during development to make it easier to find the device on the network each time.

Any ideas?

Thanks

**Comment by zteb1419** [comment]
For Pico Plus as a temporary measure I used a _.yaml_ file (in /_etc/netplan_) like this:

network:
 version: 2
 renderer: NetworkManager
 ethernets:
   eth0:
     dhcp4: no
     addresses: [192.168.2.100/24]
     routes:
     - to: default
     - via: 192.168.2.1
     nameservers:
         addresses: [192.168.2.1]

**Comment by meetroger** [comment]
I prefer a solution to generate unique mac address for each device and use dhcp.

**Comment by andrethomas** [comment]
Yup, but not a new one on each boot!

**Comment by luckfox-eng33** [comment]
You can get references from the forums
https://forums.luckfox.com/viewtopic.php?t=90

**Comment by andrethomas** [comment]
> You can get references from the forums https://forums.luckfox.com/viewtopic.php?t=90

Taking the mac from /userdata/ethaddr.txt and using it in /etc/network/interfaces as described in the forum post, e.g.

```
auto eth0
iface eth0 inet dhcp
hwaddress ether 36:45:3C:16:35:2E
```

solves this, thanks

**Comment by meetroger** [comment]
Simply put the line into the startup script:

```
if ! grep -q "hwaddress ether" /etc/network/interfaces; then echo -e "\nauto eth0\niface eth0 inet dhcp\nhwaddress ether $MACADDR" | tee -a /etc/network/interfaces > /dev/null; fi
```
