### ISSUE TITLE
Question about USB Internet Connectivity for LuckFox Pico Board with Windows 11

### ISSUE THREAD

**Issue by iz2rpn** [LuckfoxTECH/luckfox-pico#75]
Hope you're doing well! I recently got my hands on a LuckFox Pico board, and I'm curious to know if it's possible to connect it to the internet via USB, specifically using Windows 11. Could you provide information on whether the LuckFox Pico supports USB internet connectivity with Windows 11? And if it does, could you point me in the right direction on how to set it up?

Thanks a bunch!

**Comment by ZhuangZhanYu** [comment]
Hello, you can refer to this tutorial:
https://wiki.luckfox.com/Luckfox-Pico/Luckfox-Pico-Network-Sharing/
