### ISSUE TITLE
free memory (RAM), mini-a version

### ISSUE THREAD

**Issue by vjoco** [LuckfoxTECH/luckfox-pico#79]
why do I see less than 64 Mb of RAM (mini-a version), any idea?

```
luckwifi:~# free
              total        used        free      shared  buff/cache   available
Mem:          33588       12620        8180         100       12788       15788
Swap:             0           0           0
```

is it related with 
```
export RK_PARTITION_CMD_IN_ENV="32K(env),512K@32K(idblock),256K(uboot),32M(boot),512M(oem),256M(userdata),6G(rootfs),-(media)"
```
from boardconfig

would it be possible to free some allocated to gpu or similar unused hardware?

more info (dmesg)
```
[    0.000000] Kernel command line: user_debug=31 storagemedia=sd androidboot.storagemedia=sd androidboot.mode=normal  rootwait earlycon=uart8250,mmio32,0xff4c0000 console=ttyFIQ0 snd_soc_core.prealloc_buffer_size_kbytes=16 coherent_pool=0 root=/dev/mmcblk1p7 rootfstype=ext4 rk_dma_heap_cma=24M blkdevparts=mmcblk1:32K(env),512K@32K(idblock),256K(uboot),32M(boot),512M(oem),256M(userdata),6G(rootfs),-(media)

[    0.000000] Memory: 33516K/65536K available (4000K kernel code, 301K rwdata, 1836K rodata, 164K init, 133K bss, 7444K reserved, 24576K cma-reserved)
```

what is 24576K cma-reserved???

and how can it be returned to the system?

changing CONFIG_CMA_AREAS from 7 to 3 has no result

**Comment by vjoco** [comment]
would it be possible to free some allocated to gpu or similar unused hardware?

**Comment by andrethomas** [comment]
It is likely you have RAM allocated in your `BoardConfig` file using `export RK_BOOTARGS_CMA_SIZE="24M"` which is in this case reserved for camera use, but according to the [SDK Environment Deployment Documentation/Wiki](https://wiki.luckfox.com/Luckfox-Pico/Luckfox-Pico-SDK/) you can free that us for the system by changing it to 1M if you're not using camera or other hardware that uses this memory.

**Comment by vjoco** [comment]
THANKS, SOLVED I've changed to 
export RK_BOOTARGS_CMA_SIZE="1M"

[    0.000000] Memory: 57068K/65536K available (4000K kernel code, 301K rwdata, 1836K rodata, 164K init, 133K bss, 7444K reserved, **1024K cma-reserved**)

free cmd give
luckwifi:~# free
              total        used        free      shared  buff/cache   available
Mem:          57232       10440       32992         100       13800       42892
Swap:             0           0           0

I HAD TO BUILD AND FLASH ONLY THE ENV, VERY FAST
