### ISSUE TITLE
how to set/control exposure on the CSI camera?

### ISSUE THREAD

**Issue by vjoco** [LuckfoxTECH/luckfox-pico#83]
the images/video from the CSI camera are underexposed, is there a way to set the exposure time?

thanks,
Victor.

**Comment by vjoco** [comment]
Just trying to find an answer: 
 - the source sc3336.c file to generate the ko has exposure set capabilities, but the v4l driver does not list it.

**Comment by vjoco** [comment]
SOLVED:
 thanks from the info from this page: https://forums.raspberrypi.com/viewtopic.php?t=355942
Sensor controls are on the sensor's **V4L2 subdev node**,

 in my case:

v4l2-ctl -d /dev/v4l-subdev2 -l


User Controls
  -exposure 0x00980911 (int)    : min=1 max=1612 step=1 default=1280 value=299
   - horizontal_flip 0x00980914 (bool)   : default=0 value=0
   -   vertical_flip 0x00980915 (bool)   : default=0 value=0

Image Source Controls

-vertical_blanking 0x009e0901 (int)    : min=324 max=31471 step=1 default=324 value=324
 - horizontal_blanking 0x009e0902 (int)    : min=4294966492 max=4294966492 step=1 default=4294966492 value=-804 flags=read-only
  -analogue_gain 0x009e0903 (int)    : min=128 max=99614 step=1 default=128 value=128

Image Processing Controls

-link_frequency 0x009f0901 (intmenu): min=0 max=1 default=0 value=0 (253125000 0xf166188) flags=read-only
-pixel_rate 0x009f0902 (int64)  : min=0 max=102000000 step=1 default=101250000 value=101250000 flags=read-only
-test_pattern 0x009f0903 (menu)   : min=0 max=4 default=0 value=0 (Disabled)

--- then I can change with : v4l2-ctl -d /dev/v4l-subdev2 --set-ctrl=exposure=1500

--- then i can capture with: v4l2-ctl --device=/dev/video11 --set-fmt-video=width=800,height=600,pixelformat=NV12 --stream-mmap --stream-to=topo.yuv --stream-count=10

THIS WAS A HARD ONE

**Comment by vjoco** [comment]
just a capture with 
v4l2-ctl -d /dev/v4l-subdev2 --set-ctrl=exposure=555,analogue_gain=1000,vertical_flip=1

and 

v4l2-ctl --device=/dev/video11 --set-fmt-video=width=800,height=600,pixelformat=NV12 --stream-mmap --stream-to=topo.yuv --stream-count=1

loaded to https://rawpixels.net/
format yuv 420 (N21)

![image](https://github.com/LuckfoxTECH/luckfox-pico/assets/16479426/f3fb516b-4513-4ff7-a16c-eb32f4cbf7ae)

**Comment by luckfox-eng33** [comment]
Maybe the ISP is not working, you can check ` cat /proc/rkisp-vir0 `if the ISP is working 
If nothing works then run `rkaiq_3A_server`

**Comment by vjoco** [comment]
@luckfox-eng33 
thanks, I will try. Anyway, as in other system, the access to controls is done through the subdevice, not the main video device: v4l2-ctl -d /dev/v4l-subdev2 -l
