### ISSUE TITLE
How to turn off the system?

### ISSUE THREAD

**Issue by PJ5168** [LuckfoxTECH/luckfox-pico#92]
Device : Pico, Max
Image : official Ubuntu SD
Question : What's the right way to turn off the power?

1. Poweroff : system will reboot
2. Shutdown : system will reboot
3. Halt : seems working.

Is that safe and correct to turn off the power? Thanks!

**Comment by luckfox-eng33** [comment]
Halt can work normally
As long as you ensure that the file is not being read or written, it is normally safe.
shutdown and poweroff may be triggered the POR of 1106
